#!/bin/bash
# Launches all Habitat bots.

set -eo pipefail

HABITAT_HOST="${HABIBOTS_HOST-app.neohabitat.org}"
HABITAT_PORT="${HABIBOTS_PORT-1337}"
GREETER1_REGION="${HABIBOTS_GREETER1_REGION-context-welcomecenterinthatch}"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

supervisor -w "${DIR}" -- greeter.js \
  -g "${DIR}/assets/greeting.txt" \
  -s "${HABIBOTS_SLACK_TOKEN}" \
  -c "${GREETER1_REGION}" \
  -h "${HABITAT_HOST}" \
  -p "${HABITAT_PORT}" \
  -l "newavatars" \
  -u phil
