#!/bin/bash
# Launches all Habitat bots.

set -eo pipefail

HABITAT_HOST="${HABIBOTS_HOST-127.0.0.1}"
HABITAT_PORT="${HABIBOTS_PORT-1337}"
SLACK_TOKEN="${HABIBOTS_SLACK_TOKEN-xoxb-212765686899-B5qIKzJRXzNeiAuZSWAWCFQa}"
GREETER1_REGION="${HABIBOTS_GREETER1_REGION-context-Downtown_5f}"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

supervisor -w "${DIR}" -- greeter.js \
  -g "${DIR}/assets/greeting.txt" \
  -s "${SLACK_TOKEN}" \
  -c "${GREETER1_REGION}" \
  -h "${HABITAT_HOST}" \
  -p "${HABITAT_PORT}" \
  -u pcollins
